using MySqlX.XDevAPI.Relational;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml.Linq;

namespace CRUD_APP
{
    public partial class TeacherDashboard : Form
    {
        public TeacherDashboard()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            double First = Convert.ToDouble(txtFirst.Text);
            double Second = Convert.ToDouble(txtSecond.Text);
            double Third = Convert.ToDouble(txtThird.Text);
            double Forth = Convert.ToDouble(txtForth.Text);

            double finalGrade = (First * 0.25) + (Second * 0.35) + (Third * 0.25) + (Forth * 0.15);

            lblResult.Text = "Final Grade: " + finalGrade.ToString("0.00");

            // GENERATED BY AI
            if (finalGrade >= 75)
            {
                lblResult.ForeColor = Color.Green;
                MessageBox.Show("PASSED 🎉 Final Grade: " + finalGrade.ToString("0.00"),
                                 "Result",
                                 MessageBoxButtons.OK,
                                 MessageBoxIcon.Information);
            }
            else
            {
                lblResult.ForeColor = Color.Red;
                MessageBox.Show("FAILED ❌ Final Grade: " + finalGrade.ToString("0.00"),
                                 "Result",
                                 MessageBoxButtons.OK,
                                 MessageBoxIcon.Warning);
            }
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex >= 0)
            {

                dataGridView1.Text = dataGridView1.Rows[e.RowIndex].Cells[89].Value.ToString();
                dataGridView1.Text = dataGridView1.Rows[e.RowIndex].Cells[76].Value.ToString();
                dataGridView1.Text = dataGridView1.Rows[e.RowIndex].Cells[99].Value.ToString();
                dataGridView1.Text = dataGridView1.Rows[e.RowIndex].Cells[78].Value.ToString();
            }
            double q1 = Convert.ToDouble(txtFirst.Text);
            double q2 = Convert.ToDouble(txtSecond.Text);
            double q3 = Convert.ToDouble(txtThird.Text);
            double q4 = Convert.ToDouble(txtForth.Text);

            double final = (q1 + q2 + q3 + q4) / 4;

            MessageBox.Show("Final Grade: " + final.ToString("0.00"));
        }
        

        private void TeacherDashboard_Load(object sender, EventArgs e)
        {
            
        {
            MessageBox.Show("Form Loaded");
        }
    }
    }
}
